/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jaime.imagen_texto_java;

import com.jaime.imagen_texto_java.loading.hiloLoad;
import com.jaime.imagen_texto_java.loading.loadFrame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author Jymmy
 */
public class JFgestionA extends javax.swing.JFrame {

    JFileChooser selecionado = new JFileChooser();
    convertir cc = new convertir();
    File archivo = null;
    byte[] bytesImg;
    GestionA gestion = new GestionA();
    hiloLoad hLoad;
    loadFrame frame;
    String muchoTexto = "";

    /**
     * Creates new form JFgestionA
     */
    public JFgestionA() {
        initComponents();
        iniciar();
    }

    public final void iniciar() {
        frame = new loadFrame();
        hLoad = new hiloLoad(); 
        //System.out.println("==txtArea " + txtArea.getText().isEmpty());
        if (txtArea.getText().isEmpty()) {
            btnGuardarTexto.setEnabled(false);
        } else {
            btnGuardarTexto.setEnabled(true);
        }

        //System.out.println("==archivo " + archivo == null);
        if (archivo == null) {
            btnProcesar.setEnabled(false);
        } else {
            btnProcesar.setEnabled(true);
        }

        idiomasJcombo.addItem("Español");
        idiomasJcombo.addItem("Ingles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnGuardarTexto = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        idiomasJcombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertir imagenes a texto");

        btnAbrirArchivo.setText("ABRIR ARCHIVO");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblImagen);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        btnGuardarTexto.setText("GUARDAR TEXTO");
        btnGuardarTexto.setName("guardarTxt"); // NOI18N
        btnGuardarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTextoActionPerformed(evt);
            }
        });

        btnProcesar.setText("PROCESAR");
        btnProcesar.setName("procesarTxt"); // NOI18N
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jLabel1.setText("Idioma de la imagen");

        jLabel2.setText("Selecionar el idioma que viene en la imagen para realizar el proceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardarTexto)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(idiomasJcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrirArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirArchivo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idiomasJcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnGuardarTexto))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        if (selecionado.showDialog(this, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION) {
            archivo = selecionado.getSelectedFile();

            if (archivo.canRead()) {
                if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png") || archivo.getName().endsWith("gif") || archivo.getName().endsWith("JPG") || archivo.getName().endsWith("PNG") || archivo.getName().endsWith("GIF")) {
                    bytesImg = gestion.AbrirImagen(archivo);
                    lblImagen.setIcon(new ImageIcon(bytesImg));

                    ImageIcon imgIcon = (ImageIcon) lblImagen.getIcon();
                    Image imgEscalada = imgIcon.getImage().getScaledInstance(lblImagen.getWidth(),
                            lblImagen.getHeight(), Image.SCALE_SMOOTH);
                    Icon iconoEscalado = new ImageIcon(imgEscalada);
                    lblImagen.setIcon(iconoEscalado);

                    btnProcesar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Porfavor selecione un archivo de JPG o PNG");
                }
            }
        }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnGuardarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTextoActionPerformed

        if (selecionado.showDialog(this, "GUARDAR TEXTO") == JFileChooser.APPROVE_OPTION) {
            archivo = selecionado.getSelectedFile();
            if (archivo.getName().endsWith("txt")) {
                String contenido = txtArea.getText();
                String respuesta = gestion.GuardaATexto(archivo, contenido);
                if (respuesta != null) {
                    JOptionPane.showMessageDialog(rootPane, respuesta);
                    btnGuardarTexto.setEnabled(false);
                    btnProcesar.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar la texto");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "El texto debe guardarse en un formato de texto");
            }
        }
    }//GEN-LAST:event_btnGuardarTextoActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // String muchoTexto = "";
        try {
            int idioma2 = idiomasJcombo.getSelectedIndex();
            String idioma = "spa";
            if (idioma2 == 0) {
                idioma = "spa";
            } else {
                idioma = "eng";
            }          
            hLoad.iniciarHilo(frame, archivo, idioma,txtArea, Gestionarchivos.jfga);           

        } catch (Exception e) {
            muchoTexto = "" + e;
        }
        //txtArea.setText(muchoTexto);

    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFgestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFgestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFgestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFgestionA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFgestionA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnGuardarTexto;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> idiomasJcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
